                                                                                                                                                              ERROR:daisy.client:Block downscale/324 with read ROI [6400:9600, 3072:3584, 1536:2048] (3200, 512, 512) and write ROI [6400:9600, 3072:3584, 1536:2048] (3200, 512, 512) failed in worker 1695
Traceback (most recent call last):
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/client.py", line 85, in acquire_block
    yield block
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/task.py", line 179, in _process_blocks
    self.process_function(block)
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 688, in <lambda>
    process_function=lambda b: downscale_block(
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 640, in downscale_block
    out_data = skimage.measure.block_reduce(in_data, factor, np.mean)
NameError: name 'skimage' is not defined
downscale ▶:   0%|                                                                                   | 0/1764 [00:04<?, ?blocks/s, ⧗=0, ▶=38, ✔=0, ✗=889, ∅=0]                                                                                                                                                              ERROR:daisy.client:Block downscale/432 with read ROI [6400:9600, 4608:5120, 512:1024] (3200, 512, 512) and write ROI [6400:9600, 4608:5120, 512:1024] (3200, 512, 512) failed in worker 1695
Traceback (most recent call last):
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/client.py", line 85, in acquire_block
    yield block
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/task.py", line 179, in _process_blocks
    self.process_function(block)
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 688, in <lambda>
    process_function=lambda b: downscale_block(
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 640, in downscale_block
    out_data = skimage.measure.block_reduce(in_data, factor, np.mean)
NameError: name 'skimage' is not defined
downscale ▶:   0%|                                                                                   | 0/1764 [00:04<?, ?blocks/s, ⧗=0, ▶=38, ✔=0, ✗=889, ∅=0]                                                                                                                                                              ERROR:daisy.client:Block downscale/6077 with read ROI [6400:9600, 5632:6144, 9728:10240] (3200, 512, 512) and write ROI [6400:9600, 5632:6144, 9728:10240] (3200, 512, 512) failed in worker 1695
Traceback (most recent call last):
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/client.py", line 85, in acquire_block
    yield block
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/task.py", line 179, in _process_blocks
    self.process_function(block)
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 688, in <lambda>
    process_function=lambda b: downscale_block(
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 640, in downscale_block
    out_data = skimage.measure.block_reduce(in_data, factor, np.mean)
NameError: name 'skimage' is not defined
downscale ▶:   0%|                                                                                   | 0/1764 [00:05<?, ?blocks/s, ⧗=0, ▶=38, ✔=0, ✗=889, ∅=0]                                                                                                                                                              ERROR:daisy.client:Block downscale/3792 with read ROI [6400:9600, 7168:7680, 5632:6144] (3200, 512, 512) and write ROI [6400:9600, 7168:7680, 5632:6144] (3200, 512, 512) failed in worker 1695
Traceback (most recent call last):
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/client.py", line 85, in acquire_block
    yield block
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/task.py", line 179, in _process_blocks
    self.process_function(block)
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 688, in <lambda>
    process_function=lambda b: downscale_block(
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 640, in downscale_block
    out_data = skimage.measure.block_reduce(in_data, factor, np.mean)
NameError: name 'skimage' is not defined
downscale ▶:   0%|                                                                                   | 0/1764 [00:05<?, ?blocks/s, ⧗=0, ▶=38, ✔=0, ✗=889, ∅=0]